avanzu_admin_home:
  path: /demo-admin/
  defaults: {_controller: AvanzuAdminThemeBundle:Default:index}
avanzu_admin_profile:
  path: /profile/{userid}/
avanzu_admin_logout:
  path: /logout
avanzu_admin_all_tasks:
  path: /tasks/
avanzu_admin_show_task:
  path: /tasks/{taskid}/
avanzu_admin_all_notifications:
  path: /notifications/
avanzu_admin_show_notification:
  path: /notifications/{notifyid}/
avanzu_admin_all_messages:
  path: /messages/
avanzu_admin_show_message:
  path: /messages/{messageid}/



avanzu_admin_demo:
  path: /demo-admin/
  defaults: {_controller: AvanzuAdminThemeBundle:Default:index}
avanzu_admin_form_demo:
  path: /demo-admin/form-demo/
  defaults: {_controller: AvanzuAdminThemeBundle:Default:form}

avanzu_admin_dash_demo:
  path: /demo-admin/dashboard/
  defaults: {_controller: AvanzuAdminThemeBundle:Default:dashboard}

avanzu_admin_ui_gen_demo:
  path: /demo-admin/ui-elements/general/
  defaults: {_controller: AvanzuAdminThemeBundle:Default:uiGeneral}

avanzu_admin_ui_icon_demo:
  path: /demo-admin/ui-elements/icons/
  defaults: {_controller: AvanzuAdminThemeBundle:Default:uiIcons}

avanzu_admin_marionette_demo:
  path: /demo-admin/marionette
  defaults: {_controller: AvanzuAdminThemeBundle:Default:marionette}
  methods: [GET]

avanzu_admin_marionette_demo_fetch:
  path: /demo-admin/marionette/{id}
  defaults: {_controller: AvanzuAdminThemeBundle:Default:fetch}
  methods: [GET]


avanzu_admin_marionette_demo_create:
  path: /demo-admin/marionette
  defaults: {_controller: AvanzuAdminThemeBundle:Default:create}
  methods: [POST]

avanzu_admin_marionette_demo_update:
  path: /demo-admin/marionette/{id}
  defaults: {_controller: AvanzuAdminThemeBundle:Default:update}
  methods: [PUT]

avanzu_admin_marionette_demo_delete:
  path: /demo-admin/marionette/{id}
  defaults: {_controller: AvanzuAdminThemeBundle:Default:delete}
  methods: [DELETE]

