lle_alef:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

lle_user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /users

lle_admins:
    resource: "@LleAdminBundle/Resources/config/routing.yml"
    prefix:   /

lle_adminlist:
    resource: "@LleAdminListBundle/Resources/config/routing.yml"

#fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
