# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    alef_contrats_right:
        class: Lle\AlefBundle\Services\AlefContratRight
        arguments: ["@service_container"]
    alef_lieu_token:
        class: Lle\AlefBundle\Services\AlefLieuToken
        arguments: ["@service_container"]
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    fos_user.doctrine_registry:
        alias: doctrine
